site_name: hardtarget

theme:
  name: "material"
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.path
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "#002d72"
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "#002d72"
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/danielk333/hardtarget

extra_css:
  - assets/style.css

plugins:
  - search
  - section-index
  - gen-files:
      scripts:
        - docs/scripts/generate_api_docs.py
  - literate-nav:
      nav_file: nav.md
  - bibtex:
      bib_file: "docs/references.bib"
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            docstring_section_style: table
            show_docstring_functions: true
            show_docstring_modules: true
            show_docstring_description: true
            inherited_members: true
            parameter_headings: true
            type_parameter_headings: true
            show_symbol_type_toc: true
            separate_signature: true
            show_signature_annotations: true
            show_signature_type_parameters: true
            summary: true
  - mkdocs-jupyter:
      execute: true
      execute_ignore:
        - examples/extras/experiment_space.py
        - examples/extras/linearized_errors.py
        - examples/extras/plot_logo.py
        - examples/target_estimation/estimate_errors.py
        - examples/target_estimation/precision_orbit_analysis.py
        - examples/target_estimation/profile_speed.py
        - examples/back_to_basics/part3_sweep_acceleration.py
        - examples/direction_of_arrival/doa_error_per_resolution.py

      include_source: false
      ignore: ["_wip*"]
      allow_errors: false
      remove_tag_config:
        remove_input_tags:
          - hide_code

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Usage:
      - Install: usage/install.md
      - Quickstart: usage/quickstart.md
      - CLI: usage/cli.md
      - Develop: usage/develop.md
  - Analyse:
      - analyse/api_analyse.md
      - Methods:
          - Target Estimation: analyse/method/target_estimation.md
          - Optimization: analyse/method/optimization.md
          - Event Detection: analyse/method/event_detection.md
          - Direction Of Arrival: analyse/method/direction_of_arrival.md
      - Configuration parameters: analyse/config_parameters.md
      - Analysis output: analyse/format_analyse.md
      - Parallelism: analyse/parallelism.md
  - Concepts: concepts/concept_mf.md
  - Reference: reference/
  - Examples:
      - Back to basics:
          - Part 1 - Boxcar: examples/back_to_basics/part1_boxcar_fft.py
          - Part 2 - Doppler drift: examples/back_to_basics/part2_doppler_drift.py
          #- Part 3 - Sweep acceleration: examples/back_to_basics/part3_sweep_acceleration.py
          - Part 4 - Determine acceleration: examples/back_to_basics/part4_determine_acceleration.py
          - Part 5 - Ambiguity function: examples/back_to_basics/part5_ambiguity_function.py
          - Part 6 - Ipp number: examples/back_to_basics/part6_ipp_number.py
          - Part 7 - DPT Criterion: examples/back_to_basics/part7_dpt_criterion.py
          - Part 8 - Plot GMF: examples/back_to_basics/part8_plot_gmf.py
      - Target Estimation:
          - Analyse and inspect: examples/target_estimation/analyse_and_inspect.py
          - Implementation performance comparison: examples/target_estimation/implementation_performance.py
          - Visualization of analysis parameters: examples/target_estimation/visualize_analysis_parameters.py
          - Visualization of matched filter: examples/target_estimation/visualize_matched_filter.py
          - Visualization of raw data: examples/target_estimation/plot_raw_data.py
      - Optimization:
          - Optimizing Target Estimation: examples/optimization/optimization.py
      - Event Detection:
          - Event Detection: examples/event_detection/event_detection.py
      - Direction of Arrival:
          - Direction of Arrival: examples/direction_of_arrival/interferometry.py
      - Simulation:
          - Simulated tx signal: examples/simulation/simulated_tx_signal.py
          - Simulated array beam data: examples/simulation/multichannel_simulation.py
          - Analysis of simulated data: examples/simulation/analyse_simulation.py
