name: Flake8 Linting

# Run this workflow on any push or pull request to the main branch
on:
  push:
    branches:
      - dev/ingar
  pull_request:
    branches:
      - dev/ingar

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace '3.x' with the specific Python version if needed

      # Install Flake8
      - name: Install Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # Run Flake8 linting on the src folder
      - name: Run Flake8
        run: |
          flake8 src/hardtarget
