name: Linting and Testing

# Run this workflow on any push or pull request to the main branch
on:
  push:
    branches:
      - dev/ingar
  pull_request:
    branches:
      - dev/ingar

jobs:

    # venv
    venv:
        runs-on: ubuntu-latest

        steps:
            -   name: Check out repository code
                uses: actions/checkout@v4

            -   name: Install system dependencies
                run: |
                    sudo apt-get update
                    sudo apt-get install -y gcc libfftw3-dev libhdf5-dev

            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.x'

            -   name: Create virtual environment
                run: |
                    python -m venv venv
                    source venv/bin/activate
                    pip install --upgrade pip
                    pip install .[test]
                    # Save the virtual environment as an artifact
                    tar -czf venv.tar.gz venv
                    
            -   name: Upload virtual environment
                uses: actions/upload-artifact@v4
                with:
                    name: venv
                    path: venv.tar.gz


    # linting
    lint:
        runs-on: ubuntu-latest
        needs: venv

        steps:
            -   name: Check out repository code
                uses: actions/checkout@v4

            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.x'

            -   name: Download virtual environment
                uses: actions/download-artifact@v4
                with:
                    name: venv
                    path: ./

            # activate venv
            -   name: Activate virtual environment
                run: |
                    tar -xzf venv.tar.gz
                    source ./venv/bin/activate
    
            # actual linting
            -   name: Flake8 linting
                run: |
                    flake8 src/hardtarget

