# This workflow will install Python dependencies 
# and try to build and deploy the project to 
# testpypi

name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        sudo apt-get install gcc nvidia-cuda-toolkit libfftw3-dev -y
        python -m pip install --upgrade pip
        python -m pip install build twine
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build and upload to testpypi
      run: |
        python3 -m build -s